version: '3.0'
services:
  mysqldb:
    container_name: yasuki-mysqldb
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_db
    volumes:
      - ./mysql-volume:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      springboot-mysql-net:

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yasuki-spring
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_PORT: 3306
      DATABASE_NAME: db_yasuki
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:

networks:
  springboot-mysql-net: